<?php
require_once('Swat/SwatObject.php');

/**
 * Base class for all widgets
 *
 * @package Swat
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @copyright silverorange 2004
 */
abstract class SwatWidget extends SwatObject {

	/**
	 * The widget which contains this widget
	 * @var SwatContainer
	 */
	public $parent = null;

	/**
	 * A non-visible textual name for this widget, or null
	 * @var string
	 */
	public $name;

	/**
	 * Visible
	 *
	 * Whether the widget is displayed. Not all widgets respect this (yet).
	 *
	 * @var boolean
	 */
	public $visible = true;

	/**
	 * @param string $name A non-visible textual name for this widget.
	 */
	function __construct($name = null) {
		$this->name = $name;

		$this->init();
	}

	/**
	 * Generate auto name
	 *
	 * Sets the name property of this widget to an autogenerated name
	 * if the name has not yet been set.
	 */
	protected function generateAutoName() {

		static $counter = 0;

		if ($this->name !== null) return;
		$this->name = get_class($this).$counter;

		$counter++;
	}

	/**
	 * Display the widget
	 *
	 * The widget displays itself as well as recursively displays any child 
	 * widgets.
	 */
	abstract public function display();

	/**
	 * Display the widget with tidy HTML
	 *
	 * this::display() is called and the output is cleaned up.
	 */
	public function displayTidy() {
		ob_start();
		$this->display();
		$buffer = ob_get_clean();
		$tidy = ereg_replace("</?(div|p|table|td|tr|ul|li|ol|dl)[^<>]*>", "\n\\0\n", $buffer);
		$tidy = ereg_replace("\n\n", "\n", $tidy);
		echo $tidy;
	}

	/**
	 * Process the widget
	 *
	 * After a form submit, the widget processes itself as well as recursively
	 * processes any child widgets.
	 */
	public function process() {

	}

	/**
	 * Initialize the widget
	 *
	 * Run by the widget constructor.
	 */
	public function init() {

	}

	protected $error_messages = array();

	/**
	 * Add an error message
	 *
	 * Adds a new error message to this widget.  The error will be shown by the
	 * display() method as well as cause hasErrorMessage() to return true.
	 */
	abstract public function addErrorMessage($msg);

	/**
	 * Gather error messages
	 *
	 * Gather all error messages from children of this widget and this widget 
	 * itself.
	 * @return array Array of {@link SwatErrorMessage} objects.
	 */
	abstract public function gatherErrorMessages();

	/**
	 * Check for error messages
	 * @return boolean True if there is an error message in the subtree.
	 */
	abstract public function hasErrorMessage();
}

?>
